Repository intel/intel-inb-manageability, pull requests merged in 2022-06, with the labels that each got.

#133 Merge 3.0.11 into main
  build.sh
  docs/In-Band Manageability User Guide - Azure.md
  docs/In-Band Manageability User Guide - ThingsBoard.md
  docs/Manifest Parameters.md
  docs/media/In-Band Manageability User Guide - Azure/media/image87.png
  docs/media/In-Band Manageability User Guide - ThingsBoard/media/image64.png
  docs/media/In-Band Manageability User Guide - ThingsBoard/media/image65.png
  inbc-program/README.md
  inbc-program/inbc/command/command.py
  inbc-program/inbc/command/command_factory.py
  inbc-program/inbc/command/config_command.py
  inbc-program/inbc/command/ota_command.py
  inbc-program/inbc/constants.py
  inbc-program/inbc/inbc_exception.py
  inbc-program/inbc/parser.py
  inbc-program/tests/unit/test_create_command_factory.py
  inbc-program/tests/unit/test_inbc.py
  inbm-lib/inbm_common_lib/constants.py
  inbm-lib/inbm_common_lib/request_message_constants.py
  inbm-vision/Changelog.md
  inbm-vision/node-agent/fpm-template/usr/share/node-agent/version.txt
  inbm-vision/packaging/yocto/meta-intel-ese-manageability/recipes-bit-creek/bit-creek/bit-creek_3.0.11.bb
  inbm-vision/version.txt
  inbm/Changelog.md
  inbm/cloudadapter-agent/cloudadapter/agent/broker.py
  inbm/cloudadapter-agent/cloudadapter/agent/publisher.py
  inbm/cloudadapter-agent/cloudadapter/client.py
  inbm/cloudadapter-agent/cloudadapter/constants.py
  inbm/cloudadapter-agent/fpm-template/usr/share/cloudadapter-agent/thingsboard/intel_manageability_devices_version_3.3.json
  inbm/cloudadapter-agent/tests/unit/agent/test_publisher.py
  inbm/dispatcher-agent/dispatcher/config/constants.py
  inbm/dispatcher-agent/dispatcher/dispatcher_class.py
  inbm/dispatcher-agent/dispatcher/downloader.py
  inbm/dispatcher-agent/dispatcher/fota/fota.py
  inbm/dispatcher-agent/dispatcher/packagemanager/local_repo.py
  inbm/dispatcher-agent/dispatcher/packagemanager/package_manager.py
  inbm/dispatcher-agent/dispatcher/sota/constants.py
  inbm/dispatcher-agent/dispatcher/sota/os_updater.py
  inbm/dispatcher-agent/dispatcher/sota/setup_helper.py
  inbm/dispatcher-agent/dispatcher/sota/snapshot.py
  inbm/dispatcher-agent/tests/unit/test_dispatcher.py
  inbm/integration-reloaded/test/general/UPDATE_SYSTEM.sh
  inbm/packaging/yocto/common/usr.bin.inbm-telemetry
  inbm/packaging/yocto/meta-intel-ese-manageability/recipes-inb/inb/inb_3.0.11.bb
  inbm/version.txt
Labels: ISDM_Low, release

#137 add (515264) [INBM] [SOTA] Execute 'apt-get -f install -y' after update and prior to upgrade commands
  inbm/Changelog.md
  inbm/dispatcher-agent/dispatcher/sota/os_updater.py
  inbm/dispatcher-agent/tests/unit/sota/test_os_updater.py
  inbm/integration-reloaded/test/sota/SOTA_UPDATE_SUCCESS_NO_SNAPSHOT_postboot.sh
  inbm/integration-reloaded/test/sota/SOTA_UPDATE_SUCCESS_postboot.sh
Labels: ISDM_Low, SOTA

#132 Merge release 3.0.11 back to develop branch
  inbm-vision/Changelog.md
  inbm/Changelog.md
Labels: ISDM_Low, release

#136 HSD_15011248619: Added signature argument for INBC load command to fi…
  inbc-program/inbc/parser.py
  inbm-vision/Changelog.md
  inbm/Changelog.md
Labels: enhancement, ISDM_Low, INBC

#140 Fix AOTA docker remove command to send only one status message
  inbm/dispatcher-agent/dispatcher/aota/aota_command.py
Labels: ISDM_Low, AOTA_DOCKER_REMOVE

#139 (HSD 15011298374) Missing AppArmor profile entries under /sys for diagnostic agent
  inbm/Changelog.md
  inbm/diagnostic-agent/fpm-template/etc/apparmor.d/usr.bin.inbm-diagnostic
  inbm/packaging/yocto/common/usr.bin.inbm-diagnostic
Labels: bug, ISDM_Low

#141 (RTC 515263) Added support for non-LTS versions of Ubuntu
  inbm-vision/Changelog.md
  inbm-vision/installer/install-bc.sh
  inbm/Changelog.md
  inbm/cloudadapter-agent/fpm-template/usr/bin/provision-tc
  inbm/installer/install-inb.sh
  inbm/installer/install-tc.sh
Labels: enhancement, ISDM_Low, vision, INBM

#145 (HSD 15011258925) Fix Kernel modules missing after AOTA update HDDL d…
  inbm/Changelog.md
  inbm/dispatcher-agent/dispatcher/aota/application_command.py
  inbm/dispatcher-agent/tests/unit/aota/test_aota.py
Labels: ISDM_High, INBM, AOTA

#144 (RTC 515274) Docker-compose remove is not supported so removed from l…
  docs/AOTA.md
Labels: ISDM_Low, AOTA, docker_compose

#149 HSD 15011298374 Add lxc-common dependencies to .debs for AppArmor
  inbm-vision/Changelog.md
  inbm-vision/packaging/build-agent-exe-py3.sh
  inbm/Changelog.md
  inbm/fpm/fpm.sh
  inbm/packaging/build-agent-exe-py3.sh
Labels: bug, ISDM_Low

#153 Fix cloudadapter-agent disconnection issue
  inbm/Changelog.md
  inbm/telemetry-agent/telemetry/constants.py
  inbm/telemetry-agent/telemetry/tests/unit/test_telemetry_handling.py
Labels: ISDM_Medium, Thingsboard

#154 (HSD 15011231779) Updated documentation for the explanation of issue …
  docs/Configuration Parameters.md
Labels: documentation, vision, ISDM_Medium

#157 security: update golang modules for trtl
  inbm-vision/integration-reloaded/tests/intel-cert-setup-debian.sh
  inbm/Changelog.md
  inbm/integration-reloaded/test/intel-cert-setup-debian.sh
  inbm/trtl/go.mod
  inbm/trtl/go.sum
Labels: ISDM_Low, security

#156 Add log changes (to alert Validation of breaking changes in logs)
  .gitlab/merge_request_templates/Default.md
  inbm-vision/log-changes.txt
  inbm/log-changes.txt
  pull_request_template.md
Labels: release
