Repository intel/intel-inb-manageability, pull requests merged in 2022-01, with the labels that each got.

#4 Fix builds not behind Intel proxy
  inbm-vision/Changelog.md
  inbm-vision/dockerfiles/Dockerfile-check.m4
  inbm-vision/dockerfiles/commands.base-setup.m4
  inbm-vision/node-agent/fpm-template/usr/share/node-agent/version.txt
  inbm-vision/version.txt
  inbm/Changelog.md
  inbm/diagnostic-agent/diagnostic/main.py
Labels: ISDM_Low, build

#6 [506874] Fix node config schema error
  inbm-vision/Changelog.md
  inbm-vision/node-agent/fpm-template/usr/share/node-agent/intel_manageability_node_schema.xsd
Labels: bug, ISDM_Low, vision

#5 [HSD-15010407028] Fix node service not autostart after freshly flash
  inbm/Changelog.md
  inbm/packaging/yocto/meta-intel-ese-manageability/recipes-inb/inb/files/manageability-autoenable
Labels: bug, ISDM_Low, vision

#7 [HSD 15010516458] Fix storage checks failed during mender file transferring
  inbm-vision/Changelog.md
  inbm-vision/node-agent/node/constant.py
  inbm-vision/node-agent/node/space_calculator.py
Labels: bug, ISDM_Low, vision

#9 Fix the manageability docker build files
  manageability-docker/build-az-container.sh
  manageability-docker/build-tb-container.sh
Labels: ISDM_Low, build

#3 Reuse redundant document sections
  docs/Configuration Parameters.md
  docs/Error Messages.md
  docs/In-Band Manageability Developer Guide.md
  docs/In-Band Manageability Installation Guide Ubuntu.md
  docs/In-Band Manageability User Guide - Azure.md
  docs/In-Band Manageability User Guide - ThingsBoard.md
  docs/Manifest Parameters.md
  docs/Terminology.md
  docs/media/In-Band Manageability Developer Guide/media/image13.png
  docs/media/In-Band Manageability Developer Guide/media/image14.png
  docs/media/In-Band Manageability Developer Guide/media/image15.png
  inbm-vision/DeveloperChecklist.md
  inbm-vision/LICENSE
  inbm-vision/README.md
  inbm-vision/third-party-programs.txt
  inbm/DeveloperChecklist.md
  inbm/LICENSE
  inbm/README.md
  inbm/ReleasePrep.md
  inbm/fpm/mqtt/template/usr/share/doc/intel-manageability/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/third-party-programs.txt
Labels: documentation, ISDM_Low

#11 Merge v3.0.7 back to develop branch
  docs/Configuration Parameters.md
  docs/Error Messages.md
  docs/In-Band Manageability Developer Guide.md
  docs/In-Band Manageability Installation Guide Ubuntu.md
  docs/In-Band Manageability User Guide - Azure.md
  docs/In-Band Manageability User Guide - ThingsBoard.md
  docs/Manifest Parameters.md
  docs/Terminology.md
  docs/media/In-Band Manageability Developer Guide/media/image13.png
  docs/media/In-Band Manageability Developer Guide/media/image14.png
  docs/media/In-Band Manageability Developer Guide/media/image15.png
  inbc-program/inbc/broker.py
  inbc-program/inbc/constants.py
  inbm-vision/Changelog.md
  inbm-vision/DeveloperChecklist.md
  inbm-vision/LICENSE
  inbm-vision/README.md
  inbm-vision/dockerfiles/Dockerfile-check.m4
  inbm-vision/dockerfiles/commands.base-setup.m4
  inbm-vision/master-agent/master/data_handler/command_data_handler.py
  inbm-vision/third-party-programs.txt
  inbm-vision/vision-agent/vision/node_communicator/ixlink_channel_connector.py
  inbm-vision/vision-agent/vision/node_communicator/node_connector.py
  inbm/Changelog.md
  inbm/DeveloperChecklist.md
  inbm/LICENSE
  inbm/README.md
  inbm/ReleasePrep.md
  inbm/cloudadapter-agent/cloudadapter/constants.py
  inbm/cloudadapter-agent/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/configuration-agent/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/diagnostic-agent/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/dispatcher-agent/dispatcher/aota/application_command.py
  inbm/dispatcher-agent/dispatcher/dispatcher_class.py
  inbm/dispatcher-agent/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/dockerfiles/Dockerfile-check.m4
  inbm/fpm/mqtt/template/usr/share/doc/intel-manageability/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/telemetry-agent/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  inbm/telemetry-agent/telemetry/ipoller.py
  inbm/telemetry-agent/telemetry/software_bom_list.py
  inbm/third-party-programs.txt
  inbm/trtl/licenses/Intel OBL Distribution Commercial Use License 2021.pdf
  manageability-docker/build-az-container.sh
  manageability-docker/build-tb-container.sh
Labels: release, ISDM_Medium

#13 Remove files under previous master-agent directory
  inbm-vision/master-agent/master/data_handler/command_data_handler.py
  inbm-vision/master-agent/master/tests/unit/test_ota_command.py
  inbm-vision/vision-agent/fpm-template/etc/intel-manageability/public/vision-agent/intel_manageability_vision.conf
  inbm-vision/vision-agent/vision/data_handler/data_handler.py
  inbm-vision/vision-agent/vision/rollback_manager.py
Labels: ISDM_Low, vision

#14 Add bounds and default for node-agent configuration key/value pairs
  docs/Configuration Parameters.md
  inbm-lib/inbm_common_lib/validater.py
  inbm-lib/tests/unit/inbm_common_lib/test_validater.py
  inbm-vision/Changelog.md
  inbm-vision/node-agent/node/constant.py
  inbm-vision/node-agent/node/data_handler.py
Labels: ISDM_Low, vision, security

#12 Improve Developers guide
  CONTRIBUTORS.md
  docs/In-Band Manageability Developer Guide.md
  docs/In-Band Manageability Installation Guide Ubuntu.md
  docs/In-Band Manageability User Guide - Azure.md
  docs/In-Band Manageability User Guide - ThingsBoard.md
  docs/Terminology.md
  docs/media/In-Band Manageability Developer Guide/media/image1.png
  docs/media/In-Band Manageability Developer Guide/media/image3.png
  docs/media/In-Band Manageability Developer Guide/media/image5.png
  docs/media/In-Band Manageability Developer Guide/media/image6.png
  docs/media/In-Band Manageability Developer Guide/media/image7.png
  docs/media/In-Band Manageability Developer Guide/media/image8.png
  inbm-vision/node-agent/node/broker.py
  inbm-vision/node-agent/node/command/command.py
  inbm-vision/node-agent/node/command/configuration_command.py
  inbm-vision/node-agent/node/data_handler.py
  inbm-vision/node-agent/node/idata_handler.py
  inbm-vision/node-agent/node/inode.py
  inbm-vision/vision-agent/vision/node_communicator/ixlink_channel_connector.py
  inbm/trtl/README.md
Labels: documentation, ISDM_Low

#15 Add bounds and default for vision-agent configuration key/value pairs
  docs/Configuration Parameters.md
  docs/In-Band Manageability Developer Guide.md
  inbm-lib/inbm_common_lib/validater.py
  inbm-lib/tests/unit/inbm_common_lib/test_validater.py
  inbm-vision/Changelog.md
  inbm-vision/common-python-config/pyproject.toml
  inbm-vision/integration-reloaded/tests/configuration/NODE_CLIENT_CONFIG_TEST.sh
  inbm-vision/node-agent/fpm-template/usr/share/node-agent/version.txt
  inbm-vision/node-agent/node/data_handler.py
  inbm-vision/version.txt
  inbm-vision/vision-agent/vision/configuration_constant.py
  inbm-vision/vision-agent/vision/constant.py
  inbm-vision/vision-agent/vision/data_handler/data_handler.py
  inbm-vision/vision-agent/vision/registry_manager.py
  inbm-vision/vision-agent/vision/tests/unit/test_data_handler.py
  inbm-vision/vision-agent/vision/tests/unit/test_registry_manager.py
Labels: ISDM_Low, vision, security

#20 (507867) Fix bdba positives
  inbm/Changelog.md
  inbm/dockerfiles/Dockerfile-Windows.m4
  inbm/dockerfiles/image.kmb.m4
  inbm/dockerfiles/image.main.m4
  inbm/trtl/go.mod
  inbm/trtl/go.sum
  snyk/Dockerfile
Labels: ISDM_Low, security

#19 (multiple HSDs) Fix SSL search path for Yocto
  inbm/Changelog.md
  inbm/cloudadapter-agent/fpm-template/lib/systemd/system/inbm-cloudadapter.service
  inbm/dispatcher-agent/fpm-template/lib/systemd/system/inbm-dispatcher.service
Labels: bug, ISDM_Low

#23 Merge 3.0.8 to develop
  inbm-vision/Changelog.md
  inbm-vision/dockerfiles/image.kmb.m4
  inbm-vision/node-agent/fpm-template/usr/share/node-agent/version.txt
  inbm-vision/version.txt
  inbm/Changelog.md
  inbm/cloudadapter-agent/fpm-template/lib/systemd/system/inbm-cloudadapter.service
  inbm/dispatcher-agent/fpm-template/lib/systemd/system/inbm-dispatcher.service
  inbm/dockerfiles/Dockerfile-Windows.m4
  inbm/dockerfiles/image.kmb.m4
  inbm/dockerfiles/image.main.m4
  inbm/trtl/go.mod
  inbm/trtl/go.sum
  snyk/Dockerfile
Labels: ISDM_Low, release

#21 507150 Rename signature_version -> hash_algorithm in provisionNode manifest. Restrict values in manifest to 256, 384, and 512.
  docs/In-Band Manageability Developer Guide.md
  docs/Manifest Parameters.md
  inbc-program/tests/unit/test_inbc.py
  inbc-program/tests/unit/test_xlink_checker.py
  inbm-lib/inbm_common_lib/constants.py
  inbm-vision/Changelog.md
  inbm/dispatcher-agent/dispatcher/configuration_helper.py
  inbm/dispatcher-agent/dispatcher/dispatcher_class.py
  inbm/dispatcher-agent/dispatcher/fota/fota.py
  inbm/dispatcher-agent/dispatcher/fota/installer.py
  inbm/dispatcher-agent/dispatcher/ota_parser.py
  inbm/dispatcher-agent/dispatcher/ota_target.py
  inbm/dispatcher-agent/dispatcher/packagemanager/package_manager.py
  inbm/dispatcher-agent/dispatcher/provision_target.py
  inbm/dispatcher-agent/fpm-template/usr/share/dispatcher-agent/manifest_schema.xsd
  inbm/dispatcher-agent/tests/unit/aota/test_aota_command.py
  inbm/dispatcher-agent/tests/unit/fota/test_fota.py
  inbm/dispatcher-agent/tests/unit/fota/test_installer.py
  inbm/dispatcher-agent/tests/unit/sota/test_downloader.py
  inbm/dispatcher-agent/tests/unit/sota/test_os_updater.py
  inbm/dispatcher-agent/tests/unit/sota/test_os_upgrader.py
  inbm/dispatcher-agent/tests/unit/sota/test_sota.py
  inbm/dispatcher-agent/tests/unit/test_ota_downloader.py
  inbm/dispatcher-agent/tests/unit/test_ota_parser.py
  inbm/dispatcher-agent/tests/unit/test_ota_target.py
  inbm/dispatcher-agent/tests/unit/test_provision_target.py
Labels: documentation, ISDM_Low, security

#16 507152 - Update remove_file function to perform canonicalization
  inbm-lib/inbm_common_lib/utility.py
  inbm-lib/inbm_vision_lib/configuration_manager.py
  inbm-vision/vision-agent/vision/updater.py
  inbm/dispatcher-agent/dispatcher/aota/application_command.py
Labels: ISDM_Low, security

#24 Fix incorrect filenames in EHL Yocto build output
  inbm/Changelog.md
  inbm/dockerfiles/image.ehl.m4
Labels: bug, ISDM_Low

#25 (507873) Add Ubuntu 21.10 support to inbm + inbm-vision
  docs/In-Band Manageability Installation Guide Ubuntu.md
  inbm-vision/Changelog.md
  inbm-vision/installer/install-bc.sh
  inbm/Changelog.md
  inbm/cloudadapter-agent/fpm-template/usr/bin/provision-tc
  inbm/installer/install-inb.sh
  inbm/installer/install-tc.sh
Labels: ISDM_Low, ubuntu
