Repository intel/intel-inb-manageability, pull requests merged in 2023-12, with the labels that each got.

#429 Add type annotations to diagnostic-agent
  inbc-program/pyproject.toml
  inbm-lib/inbm_lib/dbs_parser.py
  inbm-lib/pyproject.toml
  inbm-lib/tests/unit/inbm_common_lib/test_shellrunner.py
  inbm-lib/tests/unit/inbm_common_lib/test_utility.py
  inbm-lib/tests/unit/inbm_common_lib/test_version.py
  inbm-lib/tests/unit/inbm_lib/test_dbs_parser.py
  inbm-lib/tests/unit/inbm_lib/test_detect_os.py
  inbm-lib/tests/unit/inbm_lib/test_version.py
  inbm-lib/tests/unit/inbm_lib/test_xmlparser.py
  inbm/cloudadapter-agent/pyproject.toml
  inbm/cloudadapter-agent/tests/unit/cloud/adapters/test_azure_adapter.py
  inbm/cloudadapter-agent/tests/unit/test_cloudadapter.py
  inbm/configuration-agent/configuration/tests/unit/test_broker.py
  inbm/configuration-agent/configuration/tests/unit/test_configuration.py
  inbm/configuration-agent/configuration/tests/unit/test_xml_key_value_store.py
  inbm/configuration-agent/pyproject.toml
  inbm/diagnostic-agent/diagnostic/command_pattern.py
  inbm/diagnostic-agent/diagnostic/docker_bench_security_runner.py
  inbm/diagnostic-agent/diagnostic/event_watcher.py
  inbm/diagnostic-agent/diagnostic/main.py
  inbm/diagnostic-agent/diagnostic/repeating_timer.py
  inbm/diagnostic-agent/mypy.ini
  inbm/diagnostic-agent/pyproject.toml
  inbm/diagnostic-agent/tests/unit/test_broker.py
  inbm/diagnostic-agent/tests/unit/test_diagnostic_checker.py
  inbm/diagnostic-agent/tests/unit/test_docker_bench_security_runner.py
  inbm/diagnostic-agent/tests/unit/test_event_watcher.py
  inbm/dispatcher-agent/dispatcher/dispatcher_class.py
  inbm/dispatcher-agent/dispatcher/packageinstaller/dbs_checker.py
  inbm/dispatcher-agent/dispatcher/provision_target.py
  inbm/dispatcher-agent/pyproject.toml
  inbm/dispatcher-agent/tests/unit/fota/test_fota.py
  inbm/dispatcher-agent/tests/unit/fota/test_guid.py
  inbm/dispatcher-agent/tests/unit/packageinstaller/test_dbs_checker.py
  inbm/dispatcher-agent/tests/unit/sota/test_snapshot.py
  inbm/dispatcher-agent/tests/unit/test_provision_target.py
Labels: AOTA

#440 Add Source commands to INBC
  inbc-program/inbc/command/command_factory.py
  inbc-program/inbc/command/source_command.py
  inbc-program/inbc/constants.py
  inbc-program/inbc/inbc.py
  inbc-program/inbc/parser.py
  inbc-program/inbc/parser/__init__.py
  inbc-program/inbc/parser/config_parser.py
  inbc-program/inbc/parser/ota_parser.py
  inbc-program/inbc/parser/parser.py
  inbc-program/inbc/parser/source_app_parser.py
  inbc-program/inbc/parser/source_os_parser.py
  inbc-program/inbc/utility.py
  inbc-program/pyproject.toml
  inbc-program/tests/unit/test_broker.py
  inbc-program/tests/unit/test_inbc.py
  inbc-program/tests/unit/test_ota_parser.py
  inbc-program/tests/unit/test_parser.py
  inbc-program/tests/unit/test_source_app_parser.py
  inbc-program/tests/unit/test_source_os_parser.py
  inbc-program/tests/unit/test_utility.py
  inbm-lib/inbm_lib/constants.py
  inbm-lib/pyproject.toml
Labels: INBC

#453 [source] Create os and application based manifest
  inbc-program/inbc/parser/source_app_parser.py
  inbc-program/inbc/parser/source_os_parser.py
  inbc-program/tests/unit/test_source_app_parser.py
  inbc-program/tests/unit/test_source_os_parser.py
  inbm/Changelog.md
  inbm/dispatcher-agent/fpm-template/usr/share/dispatcher-agent/manifest_schema.xsd
  inbm/dispatcher-agent/tests/unit/test_xmlparser.py
Labels: ISDM_Medium
