Repository intel/intel-inb-manageability, pull requests merged in 2023-11, with the labels that each got.

#412 RTC 528148-Error handler for install and uninstall scripts
  inbm/installer/install-tc.sh
  inbm/installer/uninstall-tc.sh
Labels: ISDM_Low

#418 Fix Append Config from INBC
  inbc-program/README.md
  inbc-program/inbc/command/config_command.py
  inbm/dispatcher-agent/dispatcher/dispatcher_class.py
  inbm/dispatcher-agent/tests/unit/test_dispatcher.py
Labels: ISDM_Low, Config_append

#353 [530976] Update the error message in docs
  docs/Error Messages.md
  inbm/dispatcher-agent/dispatcher/common/result_constants.py
  inbm/log-changes.txt
Labels: documentation, ISDM_Low
